# config_evaluation.yml

weights:
  CCS: 0.35
  TCS: 0.20
  ECHS: 0.15
  TQS: 0.15
  EHS: 0.05
  DRS: 0.05
  ESR: 0.05

flake8:
  ignore:
    - E501  # Ignore line length

tqs:
  max_allowable_issues: 100

ehs:
  total_exceptions_in_code: 6
  exception_classes:
    - DataProcessingError
    - APIClientError
    - ModelError
    - UtilityError
    - ServiceError
    - ValidationError
