name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # Checkout code using GITHUB_TOKEN
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Configure Git to use HTTPS with a Personal Access Token for pre-commit
    - name: Configure Git for HTTPS with PAT
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Run pre-commit hooks
    - name: Install Pre-Commit and Run Hooks
      run: |
        echo "Running pre-commit installation."
        pre-commit install
        echo "Running pre-commit hooks."
        pre-commit run --all-files

    # Run unit tests
    - name: Run Tests
      run: pytest tests/ --disable-warnings

    # Run coverage report
    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    # Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C
        radon mi src/
