name: CI - Simplified Pre-Commit with GitHub Token

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code using GitHub token
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # 2. Show Git Remote to verify Git configuration
    - name: Show Git Remote
      run: git remote -v

    # 3. Perform a Git Fetch to ensure GitHub Token authentication works
    - name: Test Git Fetch
      run: git fetch --all

    # 4. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 5. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    # 6. Configure Git to use GITHUB_TOKEN
    - name: Configure Git to use GITHUB_TOKEN
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

    # 7. Install and run pre-commit hooks with additional logging
    - name: Install and Run Pre-Commit Hooks
      run: |
        echo "Installing pre-commit hooks..."
        pre-commit install || { echo "Pre-commit installation failed."; exit 1; }
        echo "Running pre-commit hooks..."
        pre-commit run --all-files --show-diff-on-failure --verbose || { echo "Pre-commit hooks failed."; exit 1; }

    # 8. Debug pre-commit log if it fails
    - name: Debug Pre-Commit Log
      if: failure()
      run: cat /home/runner/.cache/pre-commit/pre-commit.log || echo "No pre-commit log found"
