name: CI - Pre-Commit with GitHub Token

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # 1. Checkout the code using GitHub token
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Code checked out successfully."
        ls -al

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      run: |
        echo "Python setup complete."
        python --version
        pip --version

    # 3. Install dependencies with detailed logging
    - name: Install dependencies
      run: |
        echo "Starting to install dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt || { echo "Dependency installation failed."; exit 1; }
        echo "Dependencies installed."
        pip list  # Show installed packages for debugging

    # 4. Configure Git to use GITHUB_TOKEN
    - name: Configure Git to use GITHUB_TOKEN
      run: |
        echo "Configuring Git to use GITHUB_TOKEN..."
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        git config --global credential.helper store
        git config --list
        echo "Git configured successfully."

    # 5. Install and run pre-commit hooks with extra debugging
    - name: Install Pre-Commit and Run Hooks
      run: |
        echo "Installing pre-commit hooks..."
        pre-commit install || { echo "Pre-commit installation failed."; exit 1; }
        echo "Running pre-commit hooks..."
        pre-commit run --all-files || { echo "Pre-commit hooks failed."; exit 1; }

    # 6. Debug pre-commit log if it fails
    - name: Debug Pre-Commit Log
      if: failure()  # Conditional syntax fix
      run: |
        echo "Pre-commit failed, checking log..."
        cat /home/runner/.cache/pre-commit/pre-commit.log || echo "No pre-commit log found."

    # 7. Run unit tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ --disable-warnings || { echo "Tests failed."; exit 1; }

    # 8. Run coverage report
    - name: Run Coverage
      run: |
        echo "Running coverage report..."
        coverage run -m pytest || { echo "Coverage run failed."; exit 1; }
        coverage report || { echo "Coverage report failed."; exit 1; }

    # 9. Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        echo "Analyzing code complexity using Radon..."
        radon cc src/ -s -n C || { echo "Cyclomatic complexity check failed."; exit 1; }
        radon mi src/ || { echo "Maintainability index check failed."; exit 1; }

    # 10. Check the final file structure after execution for any anomalies
    - name: Check File Structure After Execution
      run: |
        echo "Final file structure after job execution:"
        ls -R
        echo "Job completed."
