name: CI - Pre-Commit with GitHub Token

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # Checkout the code using GitHub token (to ensure secure Git operations)
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Ensure Git uses HTTPS and GitHub token for authentication
    - name: Configure Git to use GITHUB_TOKEN
      run: |
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        git config --global credential.helper store

    # Install and run pre-commit hooks
    - name: Install Pre-Commit and Run Hooks
      run: |
        echo "Running pre-commit installation."
        pre-commit install
        echo "Running pre-commit hooks."
        pre-commit run --all-files

    # Debugging pre-commit log on failure
    - name: Debug Pre-Commit Log
      if: failure()
      run: cat /home/runner/.cache/pre-commit/pre-commit.log || echo "No pre-commit log found"

    # Run unit tests
    - name: Run Tests
      run: pytest tests/ --disable-warnings

    # Run coverage report
    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    # Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C
        radon mi src/
