name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # You can add other versions if necessary

    steps:
    - uses: actions/checkout@v2

    # Set up SSH to avoid HTTPS GitHub Authentication Issues
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set Permissions for SSH Key
      run: |
        chmod 600 ~/.ssh/id_rsa

    # Manually check SSH key to debug
    - name: Check SSH Key Manually
      run: |
        ssh-add -l
        ssh-add ~/.ssh/id_rsa
        echo "Key check completed"

    # Cache Pre-Commit Environments to avoid repeated setup
    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pre-Commit and Run Hooks
      run: |
        pre-commit install
        pre-commit run --all-files

    # Debugging step: Display Pre-Commit log on failure
    - name: Display Pre-Commit Log (on failure)
      if: failure()
      run: |
        echo "Displaying pre-commit log..."
        cat precommit_debug.log

    - name: Run Tests
      run: |
        pytest tests/ --disable-warnings

    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C  # Check cyclomatic complexity for grades A, B, C
        radon mi src/  # Measure maintainability index
