name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # You can add other versions if necessary

    steps:
    - uses: actions/checkout@v2

    # Set up Git to use GITHUB_TOKEN for fetching the repositories (Forcefully apply GITHUB_TOKEN)
    - name: Force Git to Use GITHUB_TOKEN for pre-commit
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git config --global credential.helper cache
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        # Ensure that Git uses the token for all future requests
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > ~/.git-credentials
        git config --global credential.helper store

    # Cache Pre-Commit Environments to avoid repeated setup
    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Pre-Commit Hooks and Forcefully Reinitialize Environments
    - name: Install Pre-Commit and Reinitialize Environments
      run: |
        pre-commit clean
        pre-commit install
        pre-commit run --all-files

    # Debugging step: Display Pre-Commit log on failure
    - name: Display Pre-Commit Log (on failure)
      if: failure()
      run: |
        echo "Displaying pre-commit log..."
        cat /home/runner/.cache/pre-commit/pre-commit.log

    - name: Run Tests
      run: |
        pytest tests/ --disable-warnings

    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C  # Check cyclomatic complexity for grades A, B, C
        radon mi src/  # Measure maintainability index
