name: CI - Pre-Commit with Local Hook Caching

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # 1. Checkout the code using GitHub token
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # 3. Install dependencies (including pre-commit hooks)
    - name: Install dependencies and pre-cache pre-commit hooks
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt || { echo "Dependency installation failed."; exit 1; }

        echo "Installing and pre-caching pre-commit hooks..."
        pre-commit install
        pre-commit autoupdate  # Ensure all hooks are up to date
        pre-commit run --all-files || { echo "Pre-commit hook pre-run failed."; exit 1; }

    # 4. Run Pre-Commit Hooks with Local Caching (No network calls)
    - name: Run Pre-Commit Hooks with Cached Hooks
      env:
        PRE_COMMIT_HOME: /home/runner/.cache/pre-commit  # Use pre-cached directory
      run: |
        echo "Running pre-commit hooks with local caching..."
        pre-commit run --all-files --show-diff-on-failure --verbose || { echo "Pre-commit hooks failed."; exit 1; }

    # 5. Run unit tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ --disable-warnings || { echo "Tests failed."; exit 1; }

    # 6. Run coverage report
    - name: Run Coverage
      run: |
        echo "Running coverage report..."
        coverage run -m pytest || { echo "Coverage run failed."; exit 1; }
        coverage report || { echo "Coverage report failed."; exit 1; }

    # 7. Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        echo "Analyzing code complexity using Radon..."
        radon cc src/ -s -n C || { echo "Cyclomatic complexity check failed."; exit 1; }
        radon mi src/ || { echo "Maintainability index check failed."; exit 1; }

