name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Debug current directory and list files
    - name: Show current directory and list files
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    # Set up Git to use Personal Access Token (PAT) for HTTPS authentication
    - name: Set up Git to use PAT
      run: |
        git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-github-username"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Your PAT token should be stored in GitHub Secrets

    # Cache Pre-Commit Environments to avoid repeated setup
    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip freeze  # Show installed packages

    # Install Pre-Commit and Run Hooks with PAT
    - name: Install Pre-Commit and Run Hooks
      run: |
        echo "Running pre-commit installation."
        pre-commit install
        echo "Running pre-commit hooks."
        pre-commit run --all-files

    # Run unit tests
    - name: Run Tests
      run: |
        pytest tests/ --disable-warnings

    # Run Coverage report
    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    # Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C
        radon mi src/
