name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # Debugging: Show available environment variables and runner information
    - name: Show environment info
      run: |
        echo "Environment variables:"
        printenv
        echo "Runner details:"
        uname -a

    # Checkout the code using GITHUB_TOKEN for authentication
    - name: Checkout code with GITHUB_TOKEN
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Using the default GitHub token

    # Debugging: Verify the working directory and list files
    - name: Show current directory and list files
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    # Cache Pre-Commit Environments to avoid repeated setup
    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Debugging: Show Python version and environment
    - name: Show Python version
      run: |
        python --version
        pip --version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Debugging: Show installed dependencies
    - name: Show installed dependencies
      run: pip freeze

    # Install Pre-Commit and Run Hooks with debugging enabled
    - name: Install Pre-Commit and Run Hooks
      run: |
        echo "Running pre-commit installation."
        git config --global url."https://github.com/".insteadOf "git@github.com:"  # Ensure pre-commit uses HTTPS
        pre-commit install
        echo "Running pre-commit hooks."
        GIT_TRACE=1 GIT_CURL_VERBOSE=1 pre-commit run --all-files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    # Run unit tests
    - name: Run Tests
      run: |
        pytest tests/ --disable-warnings

    # Run coverage report
    - name: Run Coverage
      run: |
        coverage run -m pytest
        coverage report

    # Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        radon cc src/ -s -n C
        radon mi src/
