name: CI - Pre-Commit with GitHub Token

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # 1. Checkout the code using GitHub token
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt || { echo "Dependency installation failed."; exit 1; }

    # 4. Configure Git for Authentication using GITHUB_TOKEN
    - name: Configure Git for Authentication
      run: |
        echo "Configuring Git to use GITHUB_TOKEN for HTTPS..."
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        git config --global credential.helper store
        git config --list
        echo "Git configuration completed."

    # 5. Debug Git Configuration
    - name: Check Git Config
      run: |
        echo "Checking Git configuration..."
        git remote -v
        git config --get remote.origin.url

    # 6. Ensure pre-commit uses GITHUB_TOKEN for Git operations
    - name: Install Pre-Commit Hooks with GITHUB_TOKEN
      run: |
        echo "Installing pre-commit hooks..."
        git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        pre-commit install || { echo "Pre-commit installation failed."; exit 1; }

    # 7. Run Pre-Commit Hooks with Verbose Logging
    - name: Run Pre-Commit Hooks
      run: |
        echo "Running pre-commit hooks with verbose logging..."
        pre-commit run --all-files --show-diff-on-failure --verbose || { echo "Pre-commit hooks failed."; exit 1; }

    # 8. Debug Pre-Commit Log if it fails
    - name: Debug Pre-Commit Log
      if: failure()
      run: |
        echo "Pre-commit failed, checking log..."
        cat /home/runner/.cache/pre-commit/pre-commit.log || echo "No pre-commit log found."

    # 9. Run unit tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ --disable-warnings || { echo "Tests failed."; exit 1; }

    # 10. Run coverage report
    - name: Run Coverage
      run: |
        echo "Running coverage report..."
        coverage run -m pytest || { echo "Coverage run failed."; exit 1; }
        coverage report || { echo "Coverage report failed."; exit 1; }

    # 11. Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        echo "Analyzing code complexity using Radon..."
        radon cc src/ -s -n C || { echo "Cyclomatic complexity check failed."; exit 1; }
        radon mi src/ || { echo "Maintainability index check failed."; exit 1; }
