name: CI - Stripped Down Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code using GitHub token
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # 2. Show Git Remote to verify Git configuration
    - name: Show Git Remote
      run: git remote -v

    # 3. Test Git Fetch
    - name: Test Git Fetch
      run: git fetch --all

    # 4. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 5. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 6. Run unit tests
    - name: Run Tests
      run: |
        echo "Running tests..."
        pytest tests/ --disable-warnings || { echo "Tests failed."; exit 1; }

    # 7. Run coverage report
    - name: Run Coverage
      run: |
        echo "Running coverage report..."
        coverage run -m pytest || { echo "Coverage run failed."; exit 1; }
        coverage report || { echo "Coverage report failed."; exit 1; }

    # 8. Analyze code complexity using Radon
    - name: Analyze Code Complexity (Radon)
      run: |
        echo "Analyzing code complexity using Radon..."
        radon cc src/ -s -n C || { echo "Cyclomatic complexity check failed."; exit 1; }
        radon mi src/ || { echo "Maintainability index check failed."; exit 1; }
