name: CI - Test GitHub Token

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout using the GitHub Token
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Ensure token is passed

    # Print current git remote to see how it's configured
    - name: Show Git Remote
      run: git remote -v

    # Perform a simple Git fetch to test access
    - name: Test Git Fetch
      run: git fetch --all
